### ISSUE TITLE
Runtime error upon installation

### ISSUE THREAD

**Issue by BDEvan5** [leggedrobotics/MPC-Net#1]
Hello 

I have installed all of the dependencies and packages according to the instructions. 

Upon running the "ballbot_learner.py" file for the first time, it produces the attached error.
I ran: `python3 ballbot_learner.py`. 

![image](https://user-images.githubusercontent.com/31577482/94789798-ed060480-03c4-11eb-8a35-493a91f0c7ab.png)

The error is a RuntimeError relating to the mpc controller. How could I check what is causing the error? Is there a setting that I need to change?
Is this a problem with my installation or a bug?

Many thanks

**Comment by jcarius** [comment]
your installation looks good. The reported error states that the MPC is computing only a feedforward policy, but for our case we also need the feedback gains. To fix it, go to the file `ocs2_ballbot_example/config/mpc/task.info` and look for the property `useFeedbackPolicy`. The value has to be `1`

**Comment by BDEvan5** [comment]
That works. 
Thank you so much for your help.
